- hosts: all
  vars_files:
  - var.yml 

  tasks:
  - name: "Copying jdk software"
    copy:
      src: "{{ jdk_path }}"
      dest: "/root"

  - name: " Copying hadoop software"
    copy:
      src: "{{ hadoop_path }}"
      dest: "/root"

  - name: " Installing jdk software"
    shell: "rpm -ivh {{ jdk_software }}"
    register: Java
    ignore_errors: yes  
  - name: "Java jdk installation"
    debug:
      var: Java.stdout

  - name: " Installing hadoop software"
    shell: "rpm -ivh {{ hadoop_software }} --force"
    register: Hadoop
    ignore_errors: yes
  - name: "Hadoop installation"
    debug:
      var: Hadoop.stdout    
    


- hosts: namenode
  vars_prompt:
     - name: name_dir
       private: no
       prompt: "Enter name for  namenode directory: "

  tasks:
  - name: "Creating Namenode directory"
    file:
       state: directory
       path: "/{{ name_dir }}" 

  - name: "Copying hdfs-site.xml file"
    template:
       src: "/namenode_files/hdfs-site.xml"
       dest: "/etc/hadoop/"

  - name: "Copying core-site.xml file"
    template:
       src: "/namenode_files/core-site.xml"
       dest: "/etc/hadoop/"
 
  - name: "format the namenode"
    shell: "echo Y | hadoop namenode -format"

  - name: "Start namenode service"
    shell: "hadoop-daemon.sh start namenode"
    

  - name: "Java process"
    shell: "jps"
    register: jps
  - name: "Java Process" 
    debug:
       var: jps.stdout

  - name: "Running hadoop report"
    shell: "hadoop dfsadmin -report"
    register: report
  - name: "Showing report"
    debug:    
       var: report.stdout  



- hosts: datanode
  vars_prompt:
       - name: data_dir
         private: no
         prompt: "Enter name for datanode directory "

  tasks: 
  - name: "Creating Datanode directory"
    file:
        state: directory
        path: "/{{ data_dir }}"

  - name: "Copying hdfs-site.xml file"
    template:
        src: "/datanode_files/hdfs-site.xml"
        dest: "/etc/hadoop/"

  - name: "Copying core-site.xml file"
    template:
        src: "/datanode_files/core-site.xml"
        dest: "/etc/hadoop/"

  - name: "Start datanode service"
    shell: "hadoop-daemon.sh start datanode"

  - name: "Java process"
    shell: "jps"
    register: jps
  - name: " Java Process"
    debug:
       var: jps.stdout

  - name: "Running hadoop report"
    shell: "hadoop dfsadmin -report"
    register: report
  - name: " Showing hadoop report"
    debug:
       var: report.stdout        



- hosts: client
  tasks:
  - name: "Copying core-site.xml file"
    template:
       src: "/client/core-site.xml"
       dest: "/etc/hadoop/core-site.xml" 

  - name: "files available"
    shell: "hadoop fs -ls /"
    register: files
  - name: "Showing files"
    debug:
       var: files

          


